apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: artists
  description: Everything about artists and stuff
spec:
  owner: artist-relations-team
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: artists2
  description: Everything about artists and stuff
spec:
  owner: artist-relations-team
